name: multiple jobs on same workflow

on:
  push 


jobs:
  build_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: checking-out repo
      uses:  actions/checkout@v4

    - name: installing cowsay program
      run:  sudo apt-get install cowsay -y

    - name: Executing cowsay cmd
      run:  cowsay -f dragon "my dragon" >> dragon.txt


    - name: Sleep for 30 sec
      run:  sleep 30

  test_job:
    needs: build_jobs
    runs-on:  ubuntu-latest

    steps:
    - name: sleep for 10 sec
      run:  sleep 10

  deploy_job:
    needs:  test_job
    runs-on: ubuntu-latest

    steps:
    - name: reading file
      run:  cat dragon.txt

    - name: deploying
      run:  echo "Deploying"

    - name: end
      run:  pwd