name:   my-cowsay-workflow

on: push    ##WorkFlow needs to trigger on push event

jobs:
    first_job: ## Name of job. e.g, test, build, deploy etc
        runs-on: ubuntu-latest ## runs on virtual environment
        
        steps:
        - name: Checkout to the repo
          uses: actions/checkout@v4  ##instead of run, we use "uses"

        - name: Giving permission
          run:  chmod +x shell_script.sh
          
        - name: Running shell scriptig
          run:  ./shell_script.sh

        - name: Combining multiple commands in 1 line & checking the cow file existance. 
          run:  | ## Pipe is used to mention multiple commands
            ls -ltra
            cat README.md