name:   my-cowsay-workflow

on: push    ##WorkFlow needs to trigger on push event

jobs:
    first_job: ## Name of job. e.g, test, build, deploy etc
        runs-on: ubuntu-latest ## runs on virtual environment
        
        steps:
        - name: Checkout to the repo
          uses: actions/checkout@v4  ##instead of run, we use "uses"

        - name: Installing COWSAY Library ## To use any 3rd part library, 1st we have to install it.
          run:  sudo apt-get install cowsay -y
  

        - name: Running 3rd party library & generate ASCII Artwork
          run:  cowsay -f dragon "Running 3rd party library" >> cow.txt ##Cowsay is 3rd party library. -f is used to change the animal to dragon
        
        - name: List files
          run:  | 
           ls -ltrh
           cat README.md
           echo "My first github action script"

        ##- name: Check if file exist
          ##run:  grep -i "cow" cow.txt

        - name: Reading the cow file.
          run:  cat cow.txt

        - name: Combining multiple commands in 1 line & checking the cow file existance. 
          run:  | ## Pipe is used to mention multiple commands
            ls -ltra
            cat README.md

        - name: Executing 3rd party library (Generate ASCII Artwork)
          run: cowsay -f dragon "Run for cover, i am a dragon" >> dragon.txt ##Cosway is 3rd party library. -f is used to change animal

        ##- name: Read Files
          ##run:  cat README.md
